export const spotify = [
	{
  "tracks": [
    {
      "album": {
        "album_type": "album",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1mVhWJe3qmfTXM7ByuoryV"
            },
            "href": "https://api.spotify.com/v1/artists/1mVhWJe3qmfTXM7ByuoryV",
            "id": "1mVhWJe3qmfTXM7ByuoryV",
            "name": "The True Blue",
            "type": "artist",
            "uri": "spotify:artist:1mVhWJe3qmfTXM7ByuoryV"
          }
        ],
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "RO",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/6cnTeVjzrbD71Yyoy6K0OK"
        },
        "href": "https://api.spotify.com/v1/albums/6cnTeVjzrbD71Yyoy6K0OK",
        "id": "6cnTeVjzrbD71Yyoy6K0OK",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/317a82f9b8178ca5862beceb962b4bc2b7d0a851",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/230d9cc4823b3d2b88f60f97d9ccbafe18be6366",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/2da2394d1f37edd47f66df157e5b03840e3bd54c",
            "width": 64
          }
        ],
        "name": "Other Summer",
        "release_date": "2017-06-28",
        "release_date_precision": "day",
        "type": "album",
        "uri": "spotify:album:6cnTeVjzrbD71Yyoy6K0OK"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/1mVhWJe3qmfTXM7ByuoryV"
          },
          "href": "https://api.spotify.com/v1/artists/1mVhWJe3qmfTXM7ByuoryV",
          "id": "1mVhWJe3qmfTXM7ByuoryV",
          "name": "The True Blue",
          "type": "artist",
          "uri": "spotify:artist:1mVhWJe3qmfTXM7ByuoryV"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "RO",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA"
      ],
      "disc_number": 1,
      "duration_ms": 246242,
      "explicit": false,
      "external_ids": {
        "isrc": "TCADC1776798"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/69MRj4E8bEbIHVXASMWneS"
      },
      "href": "https://api.spotify.com/v1/tracks/69MRj4E8bEbIHVXASMWneS",
      "id": "69MRj4E8bEbIHVXASMWneS",
      "is_local": false,
      "name": "O.O.C.",
      "popularity": 38,
      "preview_url": "https://p.scdn.co/mp3-preview/fdaf1a81b607b6b5c81d894ab6f5cde238e3a3ea?cid=774b29d4f13844c495f206cafdad9c86",
      "track_number": 3,
      "type": "track",
      "uri": "spotify:track:69MRj4E8bEbIHVXASMWneS"
    },
    {
      "album": {
        "album_type": "single",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/3mIj9lX2MWuHmhNCA7LSCW"
            },
            "href": "https://api.spotify.com/v1/artists/3mIj9lX2MWuHmhNCA7LSCW",
            "id": "3mIj9lX2MWuHmhNCA7LSCW",
            "name": "The 1975",
            "type": "artist",
            "uri": "spotify:artist:3mIj9lX2MWuHmhNCA7LSCW"
          }
        ],
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "RO",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/4KZspTjVGaV9xeuaoUhEMh"
        },
        "href": "https://api.spotify.com/v1/albums/4KZspTjVGaV9xeuaoUhEMh",
        "id": "4KZspTjVGaV9xeuaoUhEMh",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/8234150cd527d51e7a7e02abad31517949e51057",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/7a1c433eb1972b683d307e3b12f53fa4e74880ef",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/9674fa59ff7422203a2ac1950cfd6ff8353e7235",
            "width": 64
          }
        ],
        "name": "Give Yourself A Try",
        "release_date": "2018-05-31",
        "release_date_precision": "day",
        "type": "album",
        "uri": "spotify:album:4KZspTjVGaV9xeuaoUhEMh"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/3mIj9lX2MWuHmhNCA7LSCW"
          },
          "href": "https://api.spotify.com/v1/artists/3mIj9lX2MWuHmhNCA7LSCW",
          "id": "3mIj9lX2MWuHmhNCA7LSCW",
          "name": "The 1975",
          "type": "artist",
          "uri": "spotify:artist:3mIj9lX2MWuHmhNCA7LSCW"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "RO",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA"
      ],
      "disc_number": 1,
      "duration_ms": 197671,
      "explicit": true,
      "external_ids": {
        "isrc": "GBK3W1800737"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/40QQZP6LVXUP5h79Q5Yvke"
      },
      "href": "https://api.spotify.com/v1/tracks/40QQZP6LVXUP5h79Q5Yvke",
      "id": "40QQZP6LVXUP5h79Q5Yvke",
      "is_local": false,
      "name": "Give Yourself A Try",
      "popularity": 69,
      "preview_url": "https://p.scdn.co/mp3-preview/1baa38e9752cee4bb800dffcf4465af2868dadc5?cid=774b29d4f13844c495f206cafdad9c86",
      "track_number": 1,
      "type": "track",
      "uri": "spotify:track:40QQZP6LVXUP5h79Q5Yvke"
    }
  ]
}
]